openapi: 3.0.0
info:
  version: '1.0'
  title: 'Reusables components'
  description: This OpenAPI document holds

paths: {}

components:
  schemas:
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
        location:
          type: string
          enum:
            - header
            - query
            - path
            - body
        name:
          type: string
        path:
          type: string
    Errors:
      required:
        - errors
      properties:
        errors:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/Error"